### PR TITLE
Specs compliant timers + clean export

### PR DESCRIPTION
**Pull request by WebReflection**
What do you think? I'm new to GJS (not to JS though) and I feel like the export pattern I see everywhere is very dirty.

In this change you have a clean export, only what is really needed goes out, and on top of that, the behavior of `setInterval` and `clearInterval` is standard as defined [in here](http://www.w3.org/TR/2011/WD-html5-20110525/timers.html#timers)

### CODE REVIEW

**Comment by WebReflection** [comment]
bump

**Comment by optimisme** [comment]
Bump?

**Comment by WebReflection** [comment]
yup, I had no answers/replies/anything until now so I've "bumped the issue" during some gardening through my PRs. If not interested, please close it, otherwise maybe you could merge?

**Comment by optimisme** [comment]
Thanks for your suggestion, I will get some of your ideas but keeping my style and removing the 'for'

**Pull request merged**
